<?php
/**
 * TL_ROOT/system/modules/agentfilter/languages/de/tl_content.php 
 * 
 * Contao extension: agentfilter 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['agent']['0'] = "User agent Suche";
$GLOBALS['TL_LANG']['tl_content']['agent']['1'] = "Überprüft, ob die angegebene Zeichenkette als Teil des user agents vorhanden ist";
$GLOBALS['TL_LANG']['tl_content']['agent_filter']['0'] = "Aktion";
$GLOBALS['TL_LANG']['tl_content']['agent_filter']['1'] = "Aktion, die abhängig vom Suchergebnis ausgeführt werden soll";
$GLOBALS['TL_LANG']['tl_content']['agent_legend'] = "User Agent Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['filter_action']['0'] = "Keine Aktion";
$GLOBALS['TL_LANG']['tl_content']['filter_action']['1'] = "Inhalt nur anzeigen, wenn die Zeichenkette im User Agent enthalten ist";
$GLOBALS['TL_LANG']['tl_content']['filter_action']['2'] = "Inhalt nur anzeigen, wenn die Zeichenkette NICHT im User Agent enthalten ist";
 
?>
